name: hotdeal
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  html: ^0.15.4
  http: ^1.1.2
  lazy_load_scrollview: ^1.3.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
  swipeable_page_route: ^0.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true